---
- name: local tasks
  hosts: localhost
  roles:
    - local

- name: setup new seedbox
  hosts: newhost
  vars:
    enabled: false
  roles:
    - feral
    - flexget
    - seedbox
    - admin
    - torrents
    - cron
